# Generated by Django 3.2.13 on 2023-02-06 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_userprofile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
    ]
